// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NavBreadcrumb: typeof import('./src/components/NavBreadcrumb/index.vue')['default']
    NavigationBreadcrumb: typeof import('./src/components/NavigationBreadcrumb/index.vue')['default']
    NavigationMenuSideBar: typeof import('./src/components/NavigationMenuSideBar/index.vue')['default']
    NavigationMenuTopBar: typeof import('./src/components/NavigationMenuTopBar/index.vue')['default']
    NavMenuSideBar: typeof import('./src/components/NavMenuSideBar/index.vue')['default']
    NavMenuTopBar: typeof import('./src/components/NavMenuTopBar/index.vue')['default']
  }
}

export { }
