// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarouselCon: typeof import('./src/components/CarouselCon/index.vue')['default']
    Configi18n: typeof import('./src/components/Configi18n/index.vue')['default']
    ConfigI18n: typeof import('./src/components/ConfigI18n/index.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NavBreadcrumb: typeof import('./src/components/NavBreadcrumb/index.vue')['default']
    NavigationBreadcrumb: typeof import('./src/components/NavigationBreadcrumb/index.vue')['default']
    NavigationMenuSideBar: typeof import('./src/components/NavigationMenuSideBar/index.vue')['default']
    NavigationMenuTopBar: typeof import('./src/components/NavigationMenuTopBar/index.vue')['default']
    NavMenuSideBar: typeof import('./src/components/NavMenuSideBar/index.vue')['default']
    NavMenuTopBar: typeof import('./src/components/NavMenuTopBar/index.vue')['default']
  }
}

export { }
